// <auto-generated />
using System;
using GestiuneRestaurant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestiuneRestaurant.Migrations
{
    [DbContext(typeof(GestiuneRestaurantContext))]
    [Migration("20260105111301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProiectRestaurant.Models.CategorieProdus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NumeCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CategorieProdus");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.Masa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacitate")
                        .HasColumnType("int");

                    b.Property<int>("NumarMasa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Masa");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.ProdusDestinat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategorieProdusID")
                        .HasColumnType("int");

                    b.Property<int>("ProdusMeniuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategorieProdusID");

                    b.HasIndex("ProdusMeniuID");

                    b.ToTable("ProdusDestinat");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.ProdusMeniu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumePreparat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("ID");

                    b.ToTable("ProdusMeniu");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.Rezervare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MasaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("MasaID");

                    b.ToTable("Rezervare");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.ProdusDestinat", b =>
                {
                    b.HasOne("ProiectRestaurant.Models.CategorieProdus", "CategorieProdus")
                        .WithMany("ProduseDestinate")
                        .HasForeignKey("CategorieProdusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectRestaurant.Models.ProdusMeniu", "ProdusMeniu")
                        .WithMany("ProduseDestinate")
                        .HasForeignKey("ProdusMeniuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieProdus");

                    b.Navigation("ProdusMeniu");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.Rezervare", b =>
                {
                    b.HasOne("ProiectRestaurant.Models.Client", "Client")
                        .WithMany("Rezervari")
                        .HasForeignKey("ClientID");

                    b.HasOne("ProiectRestaurant.Models.Masa", "Masa")
                        .WithMany("Rezervari")
                        .HasForeignKey("MasaID");

                    b.Navigation("Client");

                    b.Navigation("Masa");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.CategorieProdus", b =>
                {
                    b.Navigation("ProduseDestinate");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.Client", b =>
                {
                    b.Navigation("Rezervari");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.Masa", b =>
                {
                    b.Navigation("Rezervari");
                });

            modelBuilder.Entity("ProiectRestaurant.Models.ProdusMeniu", b =>
                {
                    b.Navigation("ProduseDestinate");
                });
#pragma warning restore 612, 618
        }
    }
}
